// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2, arg3, arg4);
}

export function ScrapeWebPage(arg1) {
  return window['go']['main']['App']['ScrapeWebPage'](arg1);
}
