// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scraper} from '../models';

export function SaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ScrapeWebPage(arg1:string):Promise<scraper.Response>;
